### ISSUE TITLE
AAC connection error

### ISSUE THREAD

**Issue by ksgithubapp** [konsolas/AAC-Issues#1072]
My server is in China, and I had set a firewall rule which is no foreign connection, no matter in or out, the aac stops working, can i please have a list of domain names that aac needs to connect, so i am able to acc it in my firewall rules.

**Comment by w-o-a-h** [comment]
try allowing spigotmc

**Comment by Janmm14** [comment]
I think you basically need to allow connections to cloudflare.

**Comment by konsolas** [comment]
See answer above

**Comment by Minemaniak** [comment]
Doesn't spigot rules state that plugin must work offline?

**Comment by Janmm14** [comment]
@Minemaniak AAC will work when you are offline.

**Comment by ksgithubapp** [comment]
@konsolas No, https://www.cloudflare.com/ips/ only have a few ips, cloudflare have way more ips than dat. And i tried to allow all the ip blocks in that website, still not getting response.

**Comment by ksgithubapp** [comment]
@Janmm14 no, AAC is not working when I'm offline

**Comment by Janmm14** [comment]
@ksgithubapp 
Ah yeah you probably also need to whitelist 5.39.90.161
The IP's listed there are actually descibing ip ranges, that's the /xx after the ips.
the tool you use for blockage likely has support for this notation.
Otherwise you are probably still able to add ip ranges somewhere, you can use this tool for calculation of start (HostMin) and end (HostMax): http://jodies.de/ipcalc?host=103.21.244.0&mask1=22&mask2=
