### ISSUE TITLE
[rubber banding]  Glitches and Bugs (Moving in Water Glitch)

### ISSUE THREAD

**Issue by FrozenBeard** [konsolas/AAC-Issues#1079]
https://www.youtube.com/watch?time_continue=82&v=KPHLd4KQoEM

Effects currently active: None

Tools And Effects:
God Armor Boots and helm:
Depth Strider 3
Respiration 3
Aqua Affinity

This Rubber Banding in water is driving players crazy.

**Comment by Slimerblue22** [comment]
Yea, hopefully this gets fixed soon. Something that seams to work for me when I get flagged is to just let AAC drag you down for a min (Stop moving for about 3-5 seconds) then start again

**Comment by CeIebrimbor** [comment]
1. Server/AAC/ProtocolLib/ViaVersion/Client Versions?
2. Please provide the detection log
3. Is this only occurring when a player eats/uses an item, or can it be replicated just with Depth Strider?

**Comment by Janmm14** [comment]
For moving issues, an aac debug log can also help to find potential issues a faster.

**Comment by Rerd** [comment]
I’ve seen this issue reported here a few times, though they might’ve been closed, not sure.

**Comment by FrozenBeard** [comment]
@CeIebrimbor I'm all up-to date, I don't see how telling you this information is going to make it "insufficient" especially if its been reported many times before, especially since this has always been a bug, no matter on the versions.

Paper Build #1​25​9 1.12.2 (Todays build) AAC 3.3.4, Using your paid configs v3.3.4 | 4 with half the checks disabled as there are so many false kicks, its unbearable for players, No ViaVersion.
Full 20 TPS.
If by logs, you mean the 1.35GB of AAC logs, how do you expect me to send those? Most are false.
https://www.dropbox.com/sh/vx92iy2cpeldnm2/AAAm7lN28dUHCig7jJ86zZE_a?dl=0
Here are the two entire logs from the 8th when the video was posted and the 7th, as for some reason AAC names the file as the 8th, but the system modify time is the 9th! 
Good luck there 8MB each.

I have previously submitted a Depth Strider bug for water rubber banding and it was supposedly fixed? maybe its the same bug with different effects? I don't know, try it. Try it with just eating and try it with depth strider. 
I will ask the player that created the video, feel free to leave comments asking more information onto the youtube video im sure he would reply, He did all the recent bug reports for me that have been driving the ENTIRE community utterly insane from how annoying they are.

**Comment by CeIebrimbor** [comment]
Sarcasm is always an efficient way to get immediate support...

The setup is almost always relevant because I have a 1.12.2 Paper server and have had no such issue. Collaborators ask for the background information to try and help, not to try to discourage you from making reports.

As @Janmm14 said, replicating this and showing a debug log of the detection is the best way to quickly find out what the issue is and how to fix it. You are correct, posting a massive log is no proactive.

**Comment by Janmm14** [comment]
We do not need general aac log files of any time.

There is a `/aacdebug` command which toggles extra debug logging which you can activate, try to reproduce the false positive and then deactivate it again. The debug log contains all movements you sent and some specialized information for konsolas. It is a server-wide command and should just be activated shortly since those files can turn really large if used over a longer time.
The debug logs will be placed in `plugins/AAC`.

The usual logs (which can be turned off in the config) are there so one could look up which exact violations led to a ban or other stuff.

**Comment by CeIebrimbor** [comment]
Haven't seen any other reports of something as hard to miss as getting kicked for swimming. Please provide the debug info and this will be re-opened @FrozenBeard 

Maybe video evidence of being kicked for using vanilla enchants/potions?
