### ISSUE TITLE
Glass Pane False Positives

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#129]
When you sprint by a glass pain, it flags for phase. Video for more detail --> https://www.youtube.com/watch?v=uuB4JJKROro    (I didn't actually make this video, I found it on youtube and it exists on v3)

**Comment by Janmm14** [comment]
Glass panes and similar blocks are not handled by AAC because they do have creepy logic and he would have to make a list of bllocks it doesn'z connect to. Also there are differences between 1.8 and 1.10 for glass panes which do not connect. 1.8 its like its connected to all sites while for 1.10 it just like a end rod.

**Comment by konsolas** [comment]
The bug appears to be quite rare, and is complex to fix due to version differences and variable hitboxes.
