### ISSUE TITLE
CPU usage of PlayerMoveEvent

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#1340]
https://timings.aikar.co/?id=0254fdbb880642cdbf89f1e361e20685

**Comment by Hyronymos** [comment]
Timings with latest aac: https://cdn.discordapp.com/attachments/416619765851881472/430011342473134101/Screenshot_1.jpg

Timings with ncp: https://cdn.discordapp.com/attachments/416619765851881472/430011402032513036/Screenshot_2.jpg

**Comment by craftrise** [comment]
**One source I would like to add: (Spigot 1.8.8 | Viaversion: YES | AAC: 3.3.13)**
- http://prntscr.com/izr7fx

**Comment by Janmm14** [comment]
This looks like some special stuff happened at the end of this timings report, because it looks good until the end.
The timings look like some players have some lag spikes ending at periodically at the same time starting at 1:00 PM, because taking the lag-only ticks show 120 move events per tick, while taking all ticks shows an average of 30 move events per tick.

**Comment by konsolas** [comment]
Move checks are just generally intensive.
