### ISSUE TITLE
Jigsaw Step bypass

### ISSUE THREAD

**Issue by jolo613** [konsolas/AAC-Issues#1390]
**Server version**: 12.2.2 (latest) Paper version git-Paper-1427 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**AAC version**: Latest (3.3.15)

**ProtocolLib version**: Latest(4.3.0)

**Plugin list**: AAC, ConditionalCommands, EpicWorldGenerator, FastAsyncWorldEdit, MaxBansPlus, ProtocolLib, SilkSpawners, SuperVanish, Teleport, UltraPermissions, WorldEdit, WorldGuard

### Configuration
Celembridor's "optimized config" latest version.

AAC Logs: [aac_2018-05-27_17-34-04.log](https://github.com/konsolas/AAC-Issues/files/2043044/aac_2018-05-27_17-34-04.log)
[aac_2018-05-27_17-26-24.log](https://github.com/konsolas/AAC-Issues/files/2043049/aac_2018-05-27_17-26-24.log)
Server log: [latest.log](https://github.com/konsolas/AAC-Issues/files/2043045/latest.log)

 How to reproduce: Set Jigsaws step to one block ( couldn't get it to go higher for some reason ) and it works. Dosen't matter whether it is in it's "vanilla" or "packet" setting both work. Worked 70% of the time. Sometimes aac would detect and stop it.
 Video : https://gyazo.com/32a4012c1e8c2f6cde713fa4e5f60d2d

**Comment by Janmm14** [comment]
1. Does celebrimbor's config have a higher fly min_vl than the default config? Did you checked with enabled verbose and AAC not always showing fly violations on step or did you just not got set backed everytime? First one would be bypass, second one would be leniency due to config.
2. Your aac log does show countless violations, not really possible to extract step out of it due to . In case it might be a bypass and not just config-related, I suggest to create an aac debug log (toggle debug logging with /aacdebug), remove cel's config out of it and uploading the debug log file here. Please keep debug logging time really short to keep the file small and the step easy to find.

**Comment by jolo613** [comment]
I'm currently not at home, but I will update the main comment with a gif of it working on your test server. I will also update the logs on a server and enable verbose.

**Comment by Janmm14** [comment]
No problem, you have time.
