### ISSUE TITLE
Setting player's veloctity triggers fly

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#1494]
AAC 3.5.0 b1
I'm making an elevator, I push the player up by running `player.setVelocity(new Vector(0, 0.04, 0));` every tick, this is how it happen.
Video:
https://www.youtube.com/watch?v=Q7HaL6GRQ9U
Debug:
https://gist.github.com/MClausz/ce919300d3dd8f34385f0c454f43dafb

**Comment by Janmm14** [comment]
The problem here is likely that AAC has no system for players recieving many velocity packets in a row. This for one prevents stuff similar to ncp bowfly, but creates issues like these.

A possible workaround for this issue would be to spawn a no-ai, invisible and invinclible entity per player where they're forced to ride on while being in the elevator and setting those entities velocity instead.

**Comment by MClausz** [comment]
I don't want to force a player to ride a invisible entity, it should be possible to fix this as older versions of AAC didn't have this issue, please re-open this issue.

**Comment by MClausz** [comment]
Can't remember, I will test it this weekend.
