### ISSUE TITLE
Hitbox Bug

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1726]
### Issue description
Hitbox check is .112 blocks off facing South and East and it's .081 blocks off facing North and West.

### Core information
**Server version**: http://prntscr.com/ou2773

**AAC version**: 4.1.3

**ProtocolLib version**: 4.3.0

**Plugin list**: If requested.

### Special environment information
**ViaVersion version**: 2.1.3

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Default configuration

**Comment by Janmm14** [comment]
how you know?

**Comment by Rerd** [comment]
reachdisplaymod

**Comment by Janmm14** [comment]
Reachdisplaymod does only provide accurate results when the enemy is standing still. Otherwise, even with 0ms ping, the client does dome sort of interpolation of the sent enemy positions.
(Short overview of that: every client tick, the player moves 1/3 towards the sent position)

I appreciate your measurement, but its not useful, AAC does of course not check with a hitbox offset to two sites by some random numbers.

**Comment by Rerd** [comment]
I was standing still hitting at complete maximum reach on my alt and my main account and in those directions I managed to  reach 3.112 facing South and East and 3.081 facing North and West. If you would like, I can record exactly how I did it, upload it here so you can re-open the issue. This isn’t invalid, I made sure to use no mods and a different Spigot version to confirm.

**Comment by konsolas** [comment]
I imagine setting hitbox.lenience to 0.1 will solve this - the values seem within margin of error. This will be made default in the next update.
