### ISSUE TITLE
When you add both time a velocity to a player, aac gives infinitive velocity to player.

### ISSUE THREAD

**Issue by yyunusyigit** [konsolas/AAC-Issues#1865]
**Issue:**

When you add async and sync velocity in same time to a player, AAC gives infinitive velocity to player. We have to do that. Because we have a lot of different system. Can you find a alternative solution for this?

What is infinitive velocity?
 - Players are flying their backwards and up.
 - A video: https://youtu.be/vXgEzaMYPew?t=494

And extra information: We have disabled "move.velocity" but nothing has changed.

### Core information
**Server version**: 1.8.8 - PaperSpigot

**AAC version**: 4.3.4 (when did you see that bug? After than version 4.2.3)

**ProtocolLib version**: 4.4.1

**Plugin list**: All are custom

### Special environment information
**ViaVersion version**:  NO

**ProtocolSupport version**:  NO

**ViaBackwards version**:  NO

**BungeeCord plugins**:  NO

**Comment by Janmm14** [comment]
As written here in the config: https://gist.github.com/konsolas/b283c1abcad3fa214d1788769c7c2db1#file-config-yml-L405
disabling move.velocity only disables the check if the client is completely ignoring velocity cheats.

Otherwise, please update your systems to only apply velocity synchroniously. Doing it sync and async doesn't give benefits. Doing it async and sync together will let the cpu gamble which packet to send last (as velocities overwrite any previous velocities)

**Comment by konsolas** [comment]
Please don't add velocity asynchronously.

**Comment by yyunusyigit** [comment]
In Today, i have tried all things with synchronously but it again gives to players infinity velocity. I think the problem is custom knocback, because we are using custom knockback system, but it works very perfectly and it doesn't contains any bug or mistake. Do you have any opinion @konsolas?

**Comment by yyunusyigit** [comment]
And logs: https://hasteb.in/ovexuyot.yaml

**Comment by armut-cat** [comment]
craftrise anti hack :P

**Comment by konsolas** [comment]
v5 - packet level velocity handling
