### ISSUE TITLE
Add in VL decay period

### ISSUE THREAD

**Issue by ChiboYen** [konsolas/AAC-Issues#2049]
Configurable VL decay would be amazing, as AAC4 had this feature which allowed specifying the period between decays AND the amount of VL decayed as well.

Current AAC5 does not allow for period adjustment, which is my suggestion.

**Comment by konsolas** [comment]
AAC5 only has continuous decay.

Previously, AAC had a repeating task with a configurable period which would iterate over all players and subtract a configured VL as necessary.

AAC5 instead uses the system time to calculate how much decay would have occurred since a player's VL was last recalculated. This is more efficient than repeating tasks for every check, which would be required to introduce some sort of period option.
