### ISSUE TITLE
v3 Config option (Speed)

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#232]
The new config (as of now) removed a few key things from Speed that allowed the end user to exchange check severity for less lag-back (possible false detections) in a few scenarios without globally altering Speed.

May I request the following be readded in speed?
   surface_speed
   underwater_speed
   item_speed
   ice_speed
(really all would be nice to have just in case, but these 4 are the top priority. Item being highest)

I also noticed a shift for velocity multipliers that were in place to compensate for high Knockback or Launchpads. I do see "vel_ticks". Does that serve an identical purpose? If so, no further requests :)

**Comment by Janmm14** [comment]
Those are removed because the values are corrected for hopefully every edge case. Even laggy players won't fail this check, because things are looked on a per-packet level that does not change in case of internet/fps lag.
Laggy players being setbacked is more the cause of the timer prevention in the speed check (packets per timeframe checks)
Knockback should be supported out-of-the-box up to level 10.
I don't know exactly what `vel_ticks` is doing atm, but I think it shouldn't be touched and maybe should be removed from the config, @konsolas might know more about that.

**Comment by CeIebrimbor** [comment]
My hill to die on is at least adding the item_speed option. @Konsolas knows why.

**Comment by konsolas** [comment]
vel_ticks does not specify a time when players are ignored, just a time where limits are slightly increased above what they have been calculated to be. It accounts for the delay between the server sending a velocity packet and the player receiving the packet.

**Comment by CeIebrimbor** [comment]
No longer an effective means of compensating (allowing) non-vanilla forms of knockback/velocity?

**Comment by konsolas** [comment]
The idea is that the knockback should be automatically handled, and that the vel_multiplier option is no longer needed. The vel_ticks is simply lag compensation.

You can experiment with it I suppose.

**Comment by CeIebrimbor** [comment]
I guess launch pads of verying magnitudes or plugin induced attack kb are the only reason for questioning. I am always a fan of "all inclusive" and if that is the case, hooray. 👍

**Comment by CeIebrimbor** [comment]
Leaving issue open for config request regarding item_speed
