### ISSUE TITLE
AAC 3 Killaura heuristics - threshold config per-sensitivity 

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#264]
Seems like a useful tool. Sens 4 autoban, sense 3 big warn sens 2 light warn or sth like that

**Comment by CeIebrimbor** [comment]
I would figure the owner sets their sensitivity and configures commands based on the # choosen. 

i.e. Sensitivity 1 but makes it staff notify only

**Comment by konsolas** [comment]
This won't be implemented inside of AAC due to the complexity of shuffling around the check framework. It can, however, be done in the API by checking violation deltas. i.e.

sensitivityOfCurrentViolation = currentHeuristicsVL - lastHeuristicsVL

These violation counts should be collected via AACAPI#getViolationLevel
