### ISSUE TITLE
Slimefun hook/compatibility?

### ISSUE THREAD

**Issue by krampo** [konsolas/AAC-Issues#358]
I believe Slimefun has an API that could be used to hook into so that AAC would be able to work alongside it. Slimefun has certain features that can't run smoothly with AAC installed. One of the biggest issues is "slimefun boots" they give you jump and a little speed boost and they don't work properly. You get launched up half way, glitch out and land back on the floor as if it was a hack. The boots give you jump effects but the plugin still blocks it.

**Comment by CeIebrimbor** [comment]
Just the boots? Or other things in Slimefun too?

**Comment by krampo** [comment]
Elytra + wind staff (gives players speed potion effect upon right click + holding the stick in hand) to allow players to fly in the world.

**Comment by krampo** [comment]
Another issue: players can't use different machines that require you to hit a crafting bench multiple times to craft an item from slimefun. It also kicks them for "fast break" because of this.

**Comment by runelynx** [comment]
This would be nice. 👍

**Comment by CeIebrimbor** [comment]
The appropriate approach to compatibility with an anti-cheat is typically a one-way street. Sounds conceited, but it's based in practicality. The 3-5 major anti-cheats(AAC, NCP, etc) can try to hook **hundreds or thousands** of non-vanilla (conflicting) plugins **or** the handful of non-vanilla plugin developers can take a minute to tie into the major anti-cheats so plugins like AAC are no muddied up trying to be all things to all people.

AAC's API is public on AAC's [Overview Page](https://www.spigotmc.org/resources/aac-advanced-anti-cheat-hack-kill-aura-blocker.6442/) on Spigot. Developers should revel at the opportunity to say their plugins are compatible with all public anti-cheat plugins. Like [this plugin](https://www.spigotmc.org/resources/vein-miner.12038/). That way, only the servers with conflicting plugins have a special hook when it notices an anti-cheat being used instead of AAC taking longer to startup and increasing download size testing for hundreds of plugins on each startup or reload.
