### ISSUE TITLE
Interact FP

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#415]
When you hit the wall then the person, or visa versa, it flags for interact.

Video: https://www.youtube.com/watch?v=8toHu3MQvVU&feature=youtu.be

Config: https://hastebin.com/uxemoremac.bash

Server Version: PaperSpigot 1.8 (Image: https://gyazo.com/35040bc1eabd9120ffd795848001ccd1)
AAC version: Newest 3.0.3
ProtocolLib version: Newest 4.20
Plugin list: 23 Plugins (Image: https://gyazo.com/8eabd7c61a96c187e005ceffefa79a99)
Special environment information
ViaVersion version: 1.0.3
ProtocolSupport version: 4.24
ViaBackwards version: None
BungeeCord plugins: 0 plugins (Clean for testing)

**Comment by CeIebrimbor** [comment]
Default config is set to never kick for interact and your cancel vl setting is 10000, so the only true issue here is you set to kick/ip-ban for interact.

Not that it is not a bug, just only a severe issue because you chose to kick/ip-ban for interact. Maybe take off the punishments and start cancelling at 10 VL since this unique case requires uncommon conditions (a lifeless player being hit into a wall at an angle and not fighting back or moving).

**Comment by SnakeDaoust1232** [comment]
I will temporarily set it to cancel but i dont like cheaters knowing if the anticheat is "picking" them up. Thats why i have the cancel vl so high. When a cheater knows that the anticheat is picking them up, they will dumb down their settings to stop them from getting banned.

**Comment by Janmm14** [comment]
You would need far higher violation levels to be able to ban a player for interact. Its also not really possible to make this check better due to how certain things are handled by the vanilla server.
