### ISSUE TITLE
Request- Multi-worlds support

### ISSUE THREAD

**Issue by Demeng7215Official** [konsolas/AAC-Issues#422]
AAC needs to support multiple worlds. I mean, after you buy the plugin, you end up using up a lot of money on Bungeecord servers because AAC does not support multiple words. Please add this.

**Comment by geNAZt** [comment]
AAC has multiworld support. We use it on Server with 2+ Worlds and never had a problem with it.

**Comment by Demeng7215Official** [comment]
Oh, maybe I am blind :)
![Uploading image.png…]()

**Comment by Janmm14** [comment]
BungeeCord Tablist plugins are compatible again since AAC 3.
This ticket asks for support of multiple worlds, however AAC does support that.
The simple thing which is incompatible is PerWorldPlugins, but that plugin was not mentioned yet in this ticket!

You can maybe get some plugin that gives permissions based on worlds so you can give your players the bypass permisssion in a certain world to emulate PerWorldPlugins.
