### ISSUE TITLE
Moved to quickly being to strict

### ISSUE THREAD

**Issue by Sikatsu** [konsolas/AAC-Issues#438]
### Issue description

Players are complaining about AAC how frequent they get the message ''It looks like you might be glitching, please tap sneak and block with your sword''. I catched an example in my latest log from King_Freakert. I will attach that log to this issue, please use CTRL + F and search for King_Freakert to find these messages. He's not the only one complaining about it, but he's one of our testers and trustworthy.

AAC Log: https://www.dropbox.com/s/6qdp9cocqga63ol/aac_2017-02-08_07-58-30.log?dl=0

### Core information
**Server version**:

git-Spigot-4741400-a1d3777 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**AAC version**: 3.0.3b1
**ProtocolLib version**: 4.2.0

**Plugin list**: If neccesary let me know.

**Comment by CeIebrimbor** [comment]
I'm commenting to mark this so I can come look in about 30 min. Make sure you update ProtocolLib to 4.2.1 for 1.11 servers.

**Comment by Sikatsu** [comment]
Whoops, I switched 2.0 with 0.2, I'm using 4.2.0 ProtocolLib. (http://prntscr.com/e63w0e)

I bet 4.2.1 is a devbuild version?

**Comment by CeIebrimbor** [comment]
I personally remove the message line and reduce item handling. AAC has the default to send that message because item detection cannot be precise enough to know if a player has stopped using an item. In uncommon circumstances, the player will be using an item (like blocking with a shield) and swap between blocking and sprinting. The client will sometimes tell the server they are using an item while sprinting for a couple seconds. The server doesn't care, but AAC does.

This is a fix for it. Or at least it seems that way:
```
   # Specific configuration options. Don't touch these unless you know what you're doing.
   # As in, unless you _actually_ know what you're doing.
   item_scalar: 0.70
   #sneak_scalar: 0.45
```

**Comment by Sikatsu** [comment]
Thanks for that information. Should I keep that # removed forever, or until a patch comes out eventually later?

**Comment by CeIebrimbor** [comment]
I don't think a patch is coming for the item situation only because I think it's not possible. The only "patch" is to ignore certain levels of item speed hacking. 

The warning message and acceptance that occasionally players will get a spike in speed detection and a lagback was pretty much pushed as the norm. This may not be the only cause for the issue discovered, but is a known issue regardless. If you find that the lagback and fps still occur, then request this issue be reopened.

**Comment by Sikatsu** [comment]
Thanks again :)

**Comment by Sikatsu** [comment]
Just received a report about this (http://prntscr.com/e674z5) will need to translate:

''After the 14th kick of today between 18:45 and 19:15 about the ''You moved to quickly'' message, when farming carrots and ofcourse sugar cane, I will create an official report.''

''AAC doesn't seem to accept farming 2 rows or 3 rows at once. Which theoretically should be possible."

''Whether the server is on high traffic or not, AAC will kick me anyway for farming.''

**Comment by Janmm14** [comment]
@Sikatsu
Please create a new ticket.
Would be to good to include verbose output (maybe also from the log files)

**Comment by Sikatsu** [comment]
Isn't that all in this ticket already? (the log)

**Comment by Janmm14** [comment]
@Sikatsu This ticket is about item-usage speed warnings, not about kicks while destroying grown food?!
At least I thought.

**Comment by CeIebrimbor** [comment]
Reports should always be specific. It should show certain cases of false detection or kicks. An issue that says "Speed check too strict" is pretty broad. A ticket like that could go endlessly with no direction and anything can be tacked onto it to muddy the clarity of the important issues.

**Comment by Sikatsu** [comment]
The message ''It looks like you might be glitching, please tap sneak and block with your sword'' and kicks for ''Moved to quickly'' happen when you destroy crops or use an EFF5 spade on sand for example.

I'm getting confused now.

**Comment by CeIebrimbor** [comment]
Read your original issue. There's nothing specific. Open up an issue for every specific case where AAC false detects or kicks.

**Comment by Sikatsu** [comment]
This seemed to be an TPS issue, now with new server hardware these bugs are all gone. Sorry for the confusement!
