### ISSUE TITLE
No detect Long Jump

### ISSUE THREAD

**Issue by ProDash1998** [konsolas/AAC-Issues#444]
Please add to antycheat long jump
https://www.youtube.com/watch?v=W1-zHhZS1SU
liest cheats  using 
✖ CHEAT EXETER:
✖ RESILIENCE:

**Comment by Photon-GitHub** [comment]
Please provide both logs and config. Did you test it yourself and verify that it is not an old version? I think this is caused by an old tolerance value. Apart from this your issue is lacking other information like the version of aac, Protocollib version, and all the other stuff you should fill in the default form.
