### ISSUE TITLE
JesusBypass(sort of) GhostHand Bypass Step Bypass NoFall Bypass(sort of)

### ISSUE THREAD

**Issue by WesleyAustin** [konsolas/AAC-Issues#460]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypass.

I have fount a way to bypass some checks with the impact client
LINK: https://www.youtube.com/watch?v=A5mmaAH8Qq8

Please include details like:
* AAC logs / Full console error
* Video of the bug / bypass, best with verbose chat output
* The ingame name of the involved players

### Core information
**1.10**: insert

****ALL OF THESE BYPASSES WERE COMPLETED ON THE AAC TEST SERVER!****
### Special environment information
Insert 'none' if you don't use it

**NONE**: insert

**NONE**: insert

**NONE**: insert

**NONE**: insert

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here: 
The 23 Feb 2017

**Comment by Rqcco** [comment]
All of these hacks have been detected towards a certain extent as seen in the video. I wouldn't really count them as a "bypass" because they would all be eventually detected. I don't think the short distance Jesus bypass will be fixed any time soon because of the complex checking of it and If fixed, it would most likely produce a lot false positives. The no fall "bypass" I guess you can argue about, but it still kicks you.

**Comment by Janmm14** [comment]
This is no nofall bypass. The getting kicked thing is not wanted by the hack client. That it does kick you at the "right" moment for 50 block height is a "lucky" accident.

The ghosthand is another lucky accident, aac would not let you open it if worldguard would allow it, but it looks like worldguard checks before aac.

Jesus/Fly check is not detecting on low distances in water due to possible false positives.

Same for bypassing step & the fly check. Thats it not working on slabs is an issue of the client.
Step detection could maybe be made stricter as a special case however.
