### ISSUE TITLE
False positives fly/speed for launchpads

### ISSUE THREAD

**Issue by MedicOP** [konsolas/AAC-Issues#489]
Launchpads trigger Fly and Speed checks. The launchpads simply set a velocity on the player upon walking over a pressure plate. 

**Server version**: 1.8.8

**AAC version**: 3.0.5-b1

**ProtocolLib version**: 4.2.0

**ViaVersion version**: 1.0.3

**Comment by CeIebrimbor** [comment]
Did you fix this?

**Comment by MedicOP** [comment]
The report was incorrect, sorry for the inconvenience

**Comment by MedicOP** [comment]
Did some more testing, issue is still happening

**Comment by Janmm14** [comment]
And fly?

**Comment by MedicOP** [comment]
Fly goes up to like 20 VL

**Comment by CeIebrimbor** [comment]
Plugin?

**Comment by MedicOP** [comment]
It's a custom plugin, this is the code:

```java
@EventHandler
public void onPlayerMove(PlayerMoveEvent event) {
    Material plate = player.getWorld().getBlockAt(player.getLocation()).getType();
    if (plate == Material.GOLD_PLATE) {
        player.setVelocity(player.getLocation().getDirection().multiply(3));
        player.setVelocity(new Vector(player.getVelocity().getX(), 1.0D, player.getVelocity().getZ()));
        player.playSound(player.getLocation(), Sound.WITHER_SHOOT, 1.0F, 1.0F);
    }
}
```

**Comment by Janmm14** [comment]
@MedicOP The problem is that you do setVelocity twice I guess.

Using this should have the same effect:
```java
@EventHandler
public void onPlayerMove(PlayerMoveEvent event) {
    if (player.getWorld().getBlockAt(player.getLocation()).getType() == Material.GOLD_PLATE) {
        player.setVelocity(player.getLocation().getDirection().multiply(3).setY(1));
    }
}
```

**Comment by MedicOP** [comment]
Shouldn't matter, the setVelocity() method just changes the motX motY motZ for the player. Setting it twice has the same result for other plugins. The PlayerVelocityEvent isn't called until the entity is ticked

**Comment by CeIebrimbor** [comment]
The appropriate approach to compatibility with an anti-cheat is typically a one-way street. Sounds conceited, but it's based in practicality. The 3-5 major anti-cheats(AAC, NCP, etc) can try to hook **hundreds or thousands** of non-vanilla (conflicting) plugins **or** the handful of non-vanilla plugin developers can take a minute to tie into the major anti-cheats so plugins like AAC are no muddied up trying to be all things to all people.

AAC's API is public on AAC's [Overview Page](https://www.spigotmc.org/resources/aac-advanced-anti-cheat-hack-kill-aura-blocker.6442/) on Spigot. Developers should revel at the opportunity to say their plugins are compatible with all public anti-cheat plugins. Like [this plugin](https://www.spigotmc.org/resources/vein-miner.12038/). That way, only the servers with conflicting plugins have a special hook when it notices an anti-cheat being used instead of AAC taking longer to startup and increasing download size testing for hundreds of plugins on each startup or reload.
