### ISSUE TITLE
Server-Crash updatePlayers ConcurrentModificationException

### ISSUE THREAD

**Issue by Phreag** [konsolas/AAC-Issues#534]
My Server started Crashing randomly yesterday after i updated PaperSpigot, AAC and a selfmade Plugin.
I Found the Issue on Github at PaperSpigot which is the same stacktrace:
[https://github.com/PaperMC/Paper/issues/644](https://github.com/PaperMC/Paper/issues/644)

We both have AAC installed and it occured after updating AAC to 3.1.2
Yesterday i downgraded AAC to 3.0.4 and the crashes stopped.

### Core information
**Server version**: PaperSpigot #1078 MC 1.11.2
**AAC version**: 3.1.2

**ProtocolLib version**: 4.2.1-SNAPSHOT-b346

**Plugin list**: LogBlock, Skinsrestorer,Griefprevention, AAC and about 50 selfmade Plugins.

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: freebungeechat, BungeeAdmintools and some selfmade Plugins

**Comment by Photon-GitHub** [comment]
I cannot be sure that AAC causes this error.

**Comment by Faxed** [comment]
Whilst I can't provide much more information here, I've found the same thing occurring as Phreag has. Since updating AAC, on the 27th March 2017, we suffered multiple crashes daily - However, we didn't immediately come to the conclusion it was AAC, given that we'd updated a number of plugins. 

Over the past week we've worked towards narrowing it down - AAC was the last plugin tested, and with it being disabled (and an older version reinstated) there have been no crashes since. Before then, it was happening 2-3 times a day - I've now gone over 24 hours without an incident since removing AAC's latest versions. 

Out of the three or so reports of this crash, over the past few days, the only common denominator is AAC - That's the only similarity that we maintain with the original poster here, as well as on the associated PaperSpigot issue post.

**Comment by Phreag** [comment]
I now can confirm that it is AAC what caused this crash for me.
I re-updated all other plugins and paperspigot to the version i used when the server crashed and the server ran stable.
When i updated AAC again to 3.1.2 the crashes started to appear again.

I dont know which action causes the server to crash, but it happens more often if more players are on a server. 
The following crash counts occured:
Main: ~20 Players - 15 Crashes/day
Second: ~15 Players - 7 Crashes/day
Mining: ~8Players - 4 Crashes/day
Third: ~3 Players - no crashes

I dont know how to help you searching for an error, its just to find the async task where you update Players but since AAC is obfuscated i cannot search the code to find the bug.

**Comment by Fluxty** [comment]
We have this exact same issue after only updating AAC to 3.1.2 in recent days

**Comment by konsolas** [comment]
I am currently uncertain of the exact nature/cause of this bug, but will investigate as as soon as possible.

**Comment by konsolas** [comment]
@Fluxty do you happen to have the full minecraft server crash report?

**Comment by Fluxty** [comment]
@konsolas 

https://hasteb.in/ovatocosuy.avrasm

https://hasteb.in/xeyehupeje.parser3

Two incidents, one on SkyBlock and the other on Prison

**Comment by craftrise** [comment]
@konsolas 

https://hastebin.com/linuvoneru.go

**Comment by konsolas** [comment]
This may be exclusive to paperspigot/spigot forks. 

AAC has an internal routine where entities are spawned and despawned in the same tick in order to pull packet metadata. In the next update, this will be done on startup. This may fix the crash issue on paper.

Thus far, we have not seen a report of this on unmodified spigot servers.

**Comment by IceString3** [comment]
My server is still crashing with AAC 3.1.3
Here's another crash report: https://pastebin.com/Ekw8NNZZ

**Comment by Fluxty** [comment]
@BOT-Neil I received that error when I was using AAC + ProtocolSupport + ClientStats, but after removing ClientStats the issue hasn't come back up. If that helps, but I don't think it's related to this so much, as with my crashing servers I had neither ProtocolSupport or ClientStats

**Comment by IceString3** [comment]
@konsolas My server is still crashing with 3.1.5 and this time it generated an hs_err_pid file.
Using PaperSpigot-1081

**Comment by Phreag** [comment]
For me it works fine now. 
Currently using AAC 3.1.4 and PaperSpigot  Build 1078

**Comment by Faxed** [comment]
I've thus far gone 24 hours without fault. Previously it was happening every few hours, repeatedly. As of 3.1.5 this no longer appears to be the case, much like what Phreag is reporting.

**Comment by IceString3** [comment]
Well, I don't really know what caused the crash, but my server has also been running fine for more than a day with latest AAC. The crash must have been caused by a plugin. However I don't know which one, but hasn't happened again, so everything is fine now.
