### ISSUE TITLE
AAC Fly Bug (Because of Plotsquared)

### ISSUE THREAD

**Issue by HaNiTLG** [konsolas/AAC-Issues#540]
#BugReport When you type in an another world (not GS world) "/plot home" (by the plugin Plotsquared), you will be kicked because of Fly. :)

**Comment by HaNiTLG** [comment]
#push

**Comment by HaNiTLG** [comment]
???

**Comment by CeIebrimbor** [comment]
Logs? Video? Still valid on AAC 3.2.0? Since this report has no info (like logs, AAC version, plugin version, video, etc), I am just going to close it. If you edit the original post to include all relevant (and required) information, please request this to be re-opened. Or create a new issue with the info.

**Comment by HaNiTLG** [comment]
"HaNiTLG commented on 6 Apr"

That's a long time.... xD
I think that the bug is fixed... xD
