### ISSUE TITLE
Failed to Handle Packet - Concurrent Modification Exception

### ISSUE THREAD

**Issue by Fluxty** [konsolas/AAC-Issues#596]
This is happening on our two PaperSpigot 1.11.2 servers with ProtocolSupport and ProtocolLib (both appropriate latest versions), Creative and Survival. They don't have many matching plugins, among them are these two and AAC. Doing a /aacreload allows the player to connect to the server again. 

Stack:
https://hasteb.in/enuvejugiy.avrasm

EDIT: These servers have the AAC version from Saturday, I will update and note again if the issue re-occurs

Others having this issue:
https://github.com/ProtocolSupport/ProtocolSupport/issues/457

We originally thought this was related to protocolsupport + clientstats or something of that nature but I believe it has more to do with AAC at this point as @BOT-Neil had mentioned in a previous issue

**Comment by CeIebrimbor** [comment]
This stack link is gone or broken. I know this has been a while since this was reported, but is this still valid? ProtocolSupport is not a supported protocolhack of AAC.

@Fluxty Please provide recent/valid evidence of this issue and request reopen or post a new issue if it is still an issue not related to ProtocolSupport.
