### ISSUE TITLE
Slowness = Speed FP (video)

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#637]
https://www.youtube.com/watch?v=mY0W038yET4
Server verson: PaperSpigot 1.11.2
AAC 3.1.6 b2
Protocollib 4.2.1 b353
logs: https://pastebin.com/QxHhebSR
(There are also some Fly FP in this logs, video coming soon)

**Comment by CeIebrimbor** [comment]
Can you establish which level of slowness this starts to occur? Slowness 6+? 8+?

This was a bug in the past that was remedied but seems to have come back with the 3.1.6 rewrite for movement. Revert to 3.1.5-b3 for temp fix.

**Comment by Janmm14** [comment]
This looks partly like an issue not bound to any particular cirumstance

**Comment by MClausz** [comment]
I'm making a gun server, players are given slowness 5 when they get shot (stun), and then they get speed fp when they tried to move while having slowness 5

**Comment by CeIebrimbor** [comment]
@Janmm14 
When players are sprinting (w/ higher than 2 slowness) and jump, the jumping through the air speed is so much different than the ground speed(more so than Slowness 1-2) that AAC sees the takeoff and landing as speed. AAC accounts for the takeoff and landing in slowness 1-2, but not any of the non-vanilla potion levels.

This issue was occurring in the past(#435) and was patched, but with the rewrite may be back?
