### ISSUE TITLE
Bypasses

### ISSUE THREAD

**Issue by timothydavidhart** [konsolas/AAC-Issues#662]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

I am able to use killaura and jesus and antikb on a client with little to no vls if you would like a copy if it to test just ask
also you can do .b on that client and crash the server

Please include details like:
I can't get a record right now i will try to get a recording soon

### Core information
**Server version**: https://gyazo.com/27265326c92113d75a0fd4266351d2d2

**AAC version**: latest 3.1.6 and also 3.1.5 b3

**ProtocolLib version**: 4.2.0

**Plugin list**: https://gyazo.com/582df6c65defa4229014980e4d09be3d

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.0.4

**ProtocolSupport version**: NONE

**ViaBackwards version**: NONE

**BungeeCord plugins**: NONE

### Reporting issues encountered on the test server has these additional rules:

AAC test server is down can't test :(

**Comment by SnakeDaoust1232** [comment]
You need more info. What client has the bypasses. And another thing. The Jesus check is disabled by default because most Jesus hacks are picked up by the fly check. You have to enable it. Another thing to keep in mind. Make sure you are not OP and make sure that the people that are testing the KillAura settings both do not have OP or bypass permissions. As for the anti-kb. I would like to see a video of that because the velocity check works fine on all my servers.

**Comment by timothydavidhart** [comment]
The crasher is using some kind of packet abuse not fully sure on how it works. the client is called "BinaryMiasma" and i made sure on both parties having permissions i went on my server with two alts that have no permissions for the killaura and made sure the killaura check works by going on my server with wurst and they get flagged for killaura,hitbox,heuristics for wurtst's KA

**Comment by SnakeDaoust1232** [comment]
Well, many killauras out there attack all entities. With that being said, i've made a post about AAC's killaura detection and how it needs improving. Plus, the hitbox check and the killaura check are inaccurate due to hitbox stretching issues. I get like 10 people a day getting false banned because of the hitbox stretching. I think and i hope that @konsolas is working on a new killaura check. As for the crash method, install viaversion and enable their packet limiter and see if the crash method still works.

**Comment by konsolas** [comment]
No logs, specific settings, or other details have been provided. Closing for the time being.
