### ISSUE TITLE
FastBreak & NoSwing

### ISSUE THREAD

**Issue by OWERLORD01** [konsolas/AAC-Issues#675]
## False Positive
FastBreak is making so many false positives when server tps is around 14 or even 15...
When tps is around 13.5 or 14, noswing is flagging every player that is just clicking or pvping.

I know that server is laggy, but you can probably auto-disable this checks when tps is low
You should probably do something with usetps: true config selection...

## Core Informations
AAC - 3.1.6-b5
AACAdditionPro - 1.9.3
ViaVersion - N/A
ProtocolSupport - Latest

### Thanks, hope you fix it soon!

**Comment by CeIebrimbor** [comment]
1. Please provide your server version, AAClogs to show this detection verbose and ProtocolLib version. I know you said latest, but that guarantees you have the wrong version because the latest is for 1.12 servers.

2. If you are having TPS drops down to 13, then you have bigger fish to fry and the last thing to worry about is the accuracy of hack detection, but that's just my personal opinion.

**Comment by OWERLORD01** [comment]
> 1. Please provide your server version, AAClogs to show this detection verbose and ProtocolLib version.

I'm using tacospigot 1.11.2 (latest), and latest protocollib version. I cant control when tps gets down, its not very often, but when something went wrong, it can get to 14 for example, and then, aac is spamming us with false positives, i added some conditional commands to stop it from banning other players, but I still want it to be fixed...

> 2. If you are having TPS drops down to 13, then you have bigger fish to fry and the last thing to worry about is the accuracy of hack detection, but that's just my personal opinion. Your claims will be heard provided you give us the evidence and not have us take your word for it.

Like i said, its only when we have so many players online... Or, for example if server is restarting, everyone from this server get to hub, and then, hub tps is lower than 13 xD and aac is spamming like crazy :)

**Comment by CeIebrimbor** [comment]
Make sure you use build 354 of ProtocolLib for 1.11 servers.

Most servers either remove of drastically reduce their anti-cheat on their HUB. Usually to accomodate their perks and jump pads (comsetic and silly perks you don't find in serious gameplay) and/or because HUB servers are known for lag when 20+ players dump into it.

My personal recomendation is for you to remove all the kicks from your HUB config or just consider disabling all checks other than Fly and Speed. I mean, do you really need to check of Killaura, NoSwing and Nuker in a place where nobody can pvp or break blocks? :)

**Comment by OWERLORD01** [comment]
Ok, thanks...
