### ISSUE TITLE
Fly fp/bug

### ISSUE THREAD

**Issue by jQuery0** [konsolas/AAC-Issues#677]
**Information**
When placing blocks under you while you cannot build, flags you for fly and speed.

Video:
https://streamable.com/53ur3

Server version: Spigot 1.9.4
AAC version: 3.1.6b5
ProtocolLib version: 4.2.1
Plugin list: ViaVersion, ProtocolLib, AAC

**Comment by SnakeDaoust1232** [comment]
https://github.com/konsolas/AAC-Issues/issues/609

**Comment by jQuery0** [comment]
Wait, what? Why is this not getting fixed. I mean, players can try to get banned/kicked without even using any hacked clients.

**Comment by Lysandr0** [comment]
@jQuery0 , see the issue referenced by @SnakeDaoust1232 and set: `reset_pitch: true`
It will not fix the problem but will mitigate it :).

The reason why this won't be fixed it's because players can abuse block glitching in a protected area to reach places where you cant access normally (thinking of a 2 high wall for example) by spamming blocks under themeselves. So AAC treats that as a cheat.

To 'resolve' this, one could make a per world/region config (like NoCheatPlus) with Speed and Fly set to just cancel without notifications or anything. This way, you don’t have to cripple any checks or changing the user’s pitch (which could be annoying in case of false positives, at least for me :p) while still blocking this specific abuse.

Another (similar) solution could be giving to players a region-specific permission to “bypass” notifications for a certain check.
(Players get checked regardless, it just doesn’t send notifications to admins/staff).

But i'm just spitballing some ideas :p

**Comment by SnakeDaoust1232** [comment]
The only thing you could do is get a custom plugin to hook into the AAC API and WorldGuard API and check if someone is doing this block glitch thing in a region that doesnt allow building. If they are, then just cancel the Violations for Speed and Fly.
