### ISSUE TITLE
Major Fly FP | 3.1.6-b5

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#690]
Info:
- Lagging out in midair, bans you for fly. If you adopted the mechanism that you used to detect if people are frozen for the velocity check, i think it would work.

Fly Config: https://hastebin.com/xovotokewi.bash

Video: https://www.youtube.com/watch?v=JDVSxJXPWhY&feature=youtu.be

Core information

Server version: TacoSpigot 1.8.8
AAC version: 3.1.6b5
ProtocolLib version: 4.2.0
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by SnakeDaoust1232** [comment]
@konsolas I also think this is worthy of the 3.1.7 milestone.

**Comment by SnakeDaoust1232** [comment]
Maybe you could add this safety measure/mechanism for the speed check as well. I've heard people are being banned for speed for similar reasons. Idk

**Comment by CeIebrimbor** [comment]
Do you mean ProtocolLib 4.2.0? Not 4.2.1 for 1.11.

**Comment by SnakeDaoust1232** [comment]
Sorry. I usually just paste my old issues over and edit the details. I missed that edit.

**Comment by SnakeDaoust1232** [comment]
Sorry. I usually just paste my old issues over and edit the details. I missed that edit.

*Although protocollib's thread on spigot says to use the latest version for 1.8-1.11. And reason why AAC doesn't like the newest version of protocollib?*

**Comment by jonesdj1** [comment]
it should work fine

**Comment by CeIebrimbor** [comment]
It _should_ work fine. The main issues I have seen have been 1.8 ViaVersion with 4.2.1. Then the issue was always fixed by reverting to 4.2.0. Since so many 1.8 servers have ViaVersion, it just became the new recommended build for 1.8 since one w/o ViaVersion would function the same with 4.2.0 or 4.2.1.

**Comment by konsolas** [comment]
I used to have complaints where hovering midair would not receive any fly violations, hence giving a player a huge advantage in games such as skywars where they could hover near the bottom of the map, not being detected as they weren't moving.

As a result, this additional detection was added to fly which checks if players are hovering midair. Otherwise, the above hacks would be possible and highly damaging on many gamemodes. 

_e.g. one could escape a fatal fall in a factions gamemode, hover midair until combat tagging expired, and then /home_
