### ISSUE TITLE
Speed potions ends - This bug is back :( | 3.1.7b1

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#738]
Info:
- Going from speed2 or speed1 to no speed, flags for speed.

Video: https://www.youtube.com/watch?v=6a6SQAMUsQQ&feature=youtu.be

Core information

Server version: Spigot, Paperspigot and Tacospigot 1.8.8
AAC version: 3.1.7b1
ProtocolLib version: 4.2.1
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by CeIebrimbor** [comment]
In the grand scheme of things, I am not too sure this is even worth pursuing. Since 99.5% of potion is via drinking (you aren't moving) or by splash which means you are only changing once. Very unlikely changing speeds more than once in a 10 second timeframe.

The bug is only exacerbated with a potion toggle feature, which no server would offer to players unless it was creative (that's my opinion).

Maybe close?

**Comment by CeIebrimbor** [comment]
@SnakeDaoust1232 Is this issue impacting your server to an extent that is worth the dev's attention? Do you offer a feature that allows players to spam toggle between potion effects?

Will close soon unless you make your case (which I am open to hear/discuss).

**Comment by Rerd** [comment]
@CeIebrimbor his server closed. I don't see this being a big issue unless a plugin that allows toggling between speed and no speed as you said.

**Comment by SnakeDaoust1232** [comment]
@Rerd My server didnt "close". Its being re-done
