### ISSUE TITLE
Can you add support for crackshot?

### ISSUE THREAD

**Issue by MatrixKhan** [konsolas/AAC-Issues#74]
Can you add support for crackshot?

**Comment by CeIebrimbor** [comment]
I think this would be rather simple, assuming Crackshot has a public API. Pretty common plugin that causes obvious issues with AAC.

**Comment by 8Marc8** [comment]
My developers will create such a plugin.
I will upload it to SpigotMC.

**Comment by CeIebrimbor** [comment]
@konsolas 
Crackshot API: https://github.com/Shampaggon/CrackShot/wiki/Hooking-into-CrackShot

**Comment by CeIebrimbor** [comment]
The appropriate approach to compatibility with an anti-cheat is typically a one-way street. Sounds conceited, but it's based in practicality. The 3-5 major anti-cheats(AAC, NCP, etc) can try to hook **hundreds or thousands** of non-vanilla (conflicting) plugins **or** the handful of non-vanilla plugin developers can take a minute to tie into the major anti-cheats so plugins like AAC are no muddied up trying to all things to all people.

AAC's API is public on AAC's [Overview Page](https://www.spigotmc.org/resources/aac-advanced-anti-cheat-hack-kill-aura-blocker.6442/) on Spigot. Developers should revel at the opportunity to say their plugins are compatible with all public anti-cheat plugins. Like [this plugin](https://www.spigotmc.org/resources/vein-miner.12038/). That way only the servers with conflicting plugins have a special hook when it notices an anti-cheat being used instead of AAC taking longer to startup and increasing download size testing for hundreds of plugins on each startup or reload.
