### ISSUE TITLE
Pingspoof check

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#75]
Some client-makers achieved to make pingspoofs that can set your ping to 1300ms - 10000ms.
You should at least implement a check that kicks the most obvious spoofers (10000ms and not lagging at all)

**Comment by Janmm14** [comment]
You peobably want to save last locations of players and check for killaura-angle / reach hacks by getting the position the player would be at according to client ping. Would make pingspoof often useless as people would get flagged for killaura.

**Comment by Photon-GitHub** [comment]
Janmm14 the ping has nothing to do with the position you can check with maths. It is pretty much random if some packet is recieved by the server now or in 200ms. Your check will very likely not work.

**Comment by konsolas** [comment]
I highly doubt such a check will work.

**Comment by Janmm14** [comment]
However if the player ping is stable, I think my check would work because the time that packet arrives is far less random?

**Comment by CeIebrimbor** [comment]
Adjusting tolerances based on ping is sketchy. I know joehot (AntiAura) takes a snap sample of the player's ping at join and adjusts the tolerance according to that ping for their **entire** session... I see players join with 100 and jump to 400 all in one session, so that's a scary concept.

Detecting for ping spoofers is possible if you throw caution to the wind(aka false positive are too likely). I've seen myself on my own server (typically 30-60ms) hit 4000ms for roughly 5 seconds and I wasn't even lagging.

I configure a rudimentary and slow Ping Spoofer detection in my config products and it makes sure players are online for more than 5 seconds, have 6000+ and are also being detected for a decent level of a hack at the same time. So it's not a dedicated ping spoofer detection, but if a player has VL 16 in Angle and has 9000ms ping without timing out, an assumption is made.

**Comment by Photon-GitHub** [comment]
The problem is that most clients don't set the ping to 5000+ but to values like 1337 (ac) or something around 1000 because almost every anticheat uses a ping limit for calculations.

**Comment by konsolas** [comment]
I think ping is going to be a bit sketchy to poke around with, especially as a check. Sometimes NMS ping values can also be buggy and report incorrectly large values, and vice versa.

**Comment by konsolas** [comment]
Pingspoof detection can still be achieved with conditionalcommands for those that want it.
