### ISSUE TITLE
MovementManager Bug

### ISSUE THREAD

**Issue by OWERLORD01** [konsolas/AAC-Issues#759]
Movement manager (AAC 3.2.0) is detecting Staff members and can ban them for hacking too.

**Comment by Slimerblue22** [comment]
I have auto bans off but yes I can confirm this. I have been getting checked/flagged for the move violation when I have aac.bypass, I do not seam to get flagged for anything else only move.

**Comment by CeIebrimbor** [comment]
The "move" check is like any other check where it bypasses the bypass check. It should not be viewed as a check like the others, but more of an internal firewall.

The easiest way to explain it is-
Move is a base packet listener for **all** off AAC's packet checks and since it does not take the typical route of a specific check(llike Speed or Fly), the bypass is incredibly hard to apply internally.

Solution = None (currently), since turning off "Move" would disable half of AAC.
