### ISSUE TITLE
No Hit Delay Macros

### ISSUE THREAD

**Issue by BlackDemonZetaxd** [konsolas/AAC-Issues#810]
I have a nohitdelay plugin, its working all okay, but the players can use a 50 clicks per second macro and it will kill the enemy in an instant and he is not instantly detected as macros  :/

**Comment by CeIebrimbor** [comment]
Video and client would be nice. And AAC/Server/ProtocolLib versions as well as Foghtspeed settings if they are altered.

**Comment by Janmm14** [comment]
I don't see any reason from my knowledge of AAC that allows autoclickers to do extra damage.
Make sure you have no plugin altering noDamageTicks of players.

**Comment by iConfueZ** [comment]
> I don't see any reason from my knowledge of AAC that allows autoclickers to do extra damage.

You can change the hit delay with the plugin No Hit Delay which means there is no delay between hits. Minecraft's default hit-delay is 20, which means that hits faster than that won't do extra damage. 

When you have an auto-clicker, while the hit delay is on 0 you can easily kill someone within 3 seconds. combat.Fightspeed needs way more fights to be able to detect an auto(double)-clicker because you are only fighting someone for 3 seconds. And if you using a non-blatant auto-clicker with an average of ~ 20 cps, it will take even longer. The only way to fix this is cancelling hits which have been flagged as potentially auto-clicker (there can be an option like some other check have).

https://streamable.com/kxjct he had full diamond with protection 4. I only had a diamond sword with unbreaking and I easily killed him in 30 seconds with a CPS of 30 (auto-clicker). He is basically saying that AAC needs way longer to detect someone with an auto-clicker because you're killing a player too fast because of the removed hit-delay.

**Comment by Janmm14** [comment]
I think the fightspeed check doesn't need an update to cancel hits, but you might not want to set your "hit delay" to 0 but maybe to 1 or 2 ticks.

Additionally there are people around which can get 20 cps with their finger, maybe not on your server but in general.
