### ISSUE TITLE
Safe Teleport Feature

### ISSUE THREAD

**Issue by UnioDex** [konsolas/AAC-Issues#84]
Hi, i made a simple parkour plugin when player fall to lava they are teleporting to start area. But AAC thinks he is using Glide, Fly or Speed. Can you add to API safeTeleport() function or something?

**Comment by konsolas** [comment]
I can't find any teleport bugs. This will probably be put on hold until it can be reproduced in AAC v3.

**Comment by CeIebrimbor** [comment]
I tested warping to unsafe locations and locations set inside blocks on v3. I think the Essentials on the server is set to safe teleport (blocks accidental detections). Maybe remove the safe teleporting in Essentials @konsolas and we can see if it's just Essentials preventing this claim on v3 test server?

I only say this because there was always some level of detection for warping in the old NormalMovements check.

**Comment by UnioDex** [comment]
I think i didn't explain well. Actually im not trying to teleport players to safe locations in Essentials language. The safeTeleport() function will teleport player without any hack checks.
