### ISSUE TITLE
AAC 3.3.0-b1 having error in my server

### ISSUE THREAD

**Issue by waiching514** [konsolas/AAC-Issues#881]
**Server version**: 1.12.1

**AAC version**: 3.3.0-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: 
![image](https://user-images.githubusercontent.com/29138111/29439333-8bd0cbee-83ef-11e7-8e5e-f16d803c332e.png)

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

Why my server have this error:
```
17.08 20:25:32 [Server] ERROR Could not pass event PlayerInteractEvent to AAC v3.3.0
17.08 20:25:32 [Server] INFO org.bukkit.event.EventException: null
17.08 20:25:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:945) [Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
17.08 20:25:32 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
17.08 20:25:32 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
17.08 20:25:32 [Server] INFO Caused by: java.lang.NullPointerException
17.08 20:25:32 [Server] INFO at me.konsolas.aac.b6.d(b6.java:70) ~[?:?]
17.08 20:25:32 [Server] INFO at me.konsolas.aac.b_.b(b_.java:47) ~[?:?]
17.08 20:25:32 [Server] INFO at me.konsolas.aac.b_.a(b_.java:33) ~[?:?]
17.08 20:25:32 [Server] INFO at me.konsolas.aac.b_.a(b_.java:89) ~[?:?]
17.08 20:25:32 [Server] INFO at sun.reflect.GeneratedMethodAccessor237.invoke(Unknown Source) ~[?:?]
17.08 20:25:32 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
17.08 20:25:32 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
17.08 20:25:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-edd0396-20ab5d3]
17.08 20:25:32 [Server] INFO ... 17 more
```

**Comment by MatheweB** [comment]
**The exact same error happens to me as well, except there is also a BlockPlace Exception:**

18.08 00:09:25 [Server] ERROR Could not pass event BlockPlaceEvent to AAC v3.3.0
18.08 00:09:25 [Server] INFO org.bukkit.event.EventException: null
18.08 00:09:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:149) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:207) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:505) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:945) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
18.08 00:09:25 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
18.08 00:09:25 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
18.08 00:09:25 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
18.08 00:09:25 [Server] INFO Caused by: java.lang.NullPointerException

**Comment by Janmm14** [comment]
@MatheweB Please look for the BlockPlaceEvent error from the start of your server log, there the exception will go on after the `Caused by`. That missing part of the error is required to kbow where it happened in AAC's code.
