### ISSUE TITLE
Resend block packet on phase check

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#893]
For instance, in a prison server a player breaks block way to fast and lead to an invisible block issue, player get stuck on that block because of phase check and can't move.
If this kind of feature is added, it may be useful in those case.

**Comment by jiangdashao** [comment]
seems like #828 ?

**Comment by CeIebrimbor** [comment]
@MClausz This is a client to server rendering issue that exists when servers have obscene block break speeds. So fast that the server and client aren't always on the same page. The "invisible block" is on the client side (because the client thinks the block broke), but in reality, the block did not break and the server still sees stone (or coal, netherrack, etc). When the client tries to move through the block, it expects air. 

AAC gives priority to the server, so this illegal movement is still seen as Phase. And rightly so because the glitch is caused by the client.

Are you asking AAC to fix a glitch caused by OP enchants? Not sure it is AAC's business to fix vanilla (or plugin) induced glitches.

**Comment by CeIebrimbor** [comment]
> seems like #828 ?

It is not

**Comment by konsolas** [comment]
Put /aacrestorechunk {player} somewhere in the phase thresholds section.
