### ISSUE TITLE
Run interact check in creative mode?

### ISSUE THREAD

**Issue by krysppy** [konsolas/AAC-Issues#943]
### Issue description
When you are breaking blocks with Nuker, (tested with Wurst) it seems that you were allowed to break any block around you, even if you weren't _swinging_ or _facing_ them.

Note: was tested in Creative Mode (also, is there a config specifically for Creative servers?)

### Core information
**Server version**: 1.12.1

**AAC version**: 3.3.1

**ProtocolLib version**: 4.3.0

**Plugin list**: AAC, ProtocolLib

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Default

**Comment by w-o-a-h** [comment]
idk why you would use a anticheat on a creative server lol

**Comment by Janmm14** [comment]
AAC does not check many things in creative mode.

**Comment by krysppy** [comment]
im saying the things it should check on a creative server should work

**Comment by CeIebrimbor** [comment]
Is this now a feature request? Because currently, AAC disables block interaction and movement checks when a player is in Creative or Spectator gamemode. AAC was designed and advertises for use on Survival/PvP/Minigame/Faction/McMMO servers. All you really need on Creative servers is basic block checks and speed. Maybe consider NoCheatPlus on your creative server(s).

**Comment by Janmm14** [comment]
This would probably require #977 to not annoy people in creative mode.

**Comment by konsolas** [comment]
AAC isn't designed as a creative mode anticheat.

NCP has additional checks for creative mode, such as CreativeFly (checking fly speed and direction) and also runs all its block breaking checks in creative. I recommend this if you need an anticheat for a creative mode server.
