### ISSUE TITLE
Velocity False Positive and some kind of bypass

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#946]
If you need more details I will give more, this is something small.
https://youtu.be/_0pK-VFuZL8

**Comment by GeoGamerLP** [comment]
This is a quite critical FP as this can be used malificiously to move long distances very fast (60 blocks (10 blocks falling)).
This FP actually also happens when you move from the ladder midair.
If you toggle fly away from the ladders with a certain motion (has to be high enough, but not too high), you will be setbacked to the ladder (if your speed VL is high enough) and get speed and velocity flags.
If you leave the ladder again (legit), you will get another velocity flags which boosts you away. Depending on the motion, you can travel to the distance above and even more

I tested this with the vanillafly of Liquidbounce (with a value of 4.6 for vanillafly), but this should also work with other client.
If you have Liquidbounce's aac velocity activated while doing this, you even have a sort of glide which goes a bit further for long distances (flags as hell though).

**Comment by Slimerblue22** [comment]
Oh...I didn't think that far into it. I just saw doing that thing on ladders caused a bug.

**Comment by CeIebrimbor** [comment]
Closing in favor of #973 (has more info)

**Comment by Slimerblue22** [comment]
Alright
