### ISSUE TITLE
Killaura normal false positive (due to close distance?)

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#952]
### Issue description
When you are close to the player you're pvping against, you get flagged for killaura normal. 

Video:
https://youtu.be/dlZu53TZhfc

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.2-b2

**ProtocolLib version**: 4.2.0

**Plugin list**: ViaVersion, ProtocolLib, AAC

### Special environment information
**ViaVersion version**: 1.2.0

### Configuration
Default configuration. Happens also on AAC's test server.

**Comment by CeIebrimbor** [comment]
I know later versions of AAC have struggled with player velocity and how it impacts player position. Hitbox recently got a wave of attention since it is much more sensitive. Looks like Killaura needs the same touch.

Setting `min_dist` higher can help drastically with this issue (attacking in close range). But just be wary of setting it above 3.0 due to bypasses for targets inside the 3 block bubble.

**Comment by iConfueZ** [comment]
I tried setting it to 2.8 but it still happens then.

**Comment by Rerd** [comment]
For my Killlaura Normal check, I made the check chance at 70, the min distance to 3.4 and the duration to 10 ticks. I also made it only ban players with 170-1 ping because higher would cause false positives. Anything with lower reach or lower CPS would bypass but heuristics will get them. With these settings I have had no false positives.

**Comment by Rerd** [comment]
[Video here](https://youtu.be/3UeaU3XDcmQ)

I feel like I should put this video here. I encountered the same problem without speed this time.

**Comment by konsolas** [comment]
Can be addressed by increasing the min_dist for the check to run.
