### ISSUE TITLE
Speed FPs with instantly breaking blocks in a protected area

### ISSUE THREAD

**Issue by Nvaros** [konsolas/AAC-Issues#962]
If you keep destroying a protected block which breaks instantly (TNT, slimes, grass etc.) with food, a sword or a bow, you will be flagged for "<Player> failed Speed: tried to toggle use too quickly" (39-40 toggles/second). The VLs are increasing really fast (~3 flags/second). Tested with Vanilla 1.8.8 (latest AAC version).

**Comment by CeIebrimbor** [comment]
Fixable with Speed setting `max_use_toggles`

**Comment by Janmm14** [comment]
That is not a fix, but a workaround.

**Comment by CeIebrimbor** [comment]
The developer of AAC uses that [reasoning for severe bugs](https://github.com/konsolas/AAC-Issues/issues/929#issuecomment-329990053), so I figured a compatibility bug wouldn't get special treatment.

Fun fact: Another report was closed because [the user changed a setting](https://github.com/konsolas/AAC-Issues/issues/956#issuecomment-329992311) that was recommended as a fix for another bug.

I guess all I expected was consistency ¯\_(ツ)_/¯

**Comment by konsolas** [comment]
use counting logic was changed since the above date, so I'm going to close this for inactivity.
