### ISSUE TITLE
Phase Bug (not critical)

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#969]
### Issue description
Couldn't do this on my test server (probably because of ping), but I did this on Hysteria PvP. It still works with default config though. Sometimes AAC doesn't tp the player outside of the block.
[Video Here](https://www.youtube.com/watch?v=GbWvZac8Ka4)

### Core information
**Server version**: unknown

**AAC version**: unknown (still exists though)

**ProtocolLib version**: unknown

**Plugin list**: unknown

### Configuration
unknown

**Comment by CeIebrimbor** [comment]
The default config does not kick for Phase. Not to say this is not a bug, but the server is going beyond the recommendations for Phase handling.

In any case, we would need far more information as it relates to the environment since nothing can be assumed. If you can replicate it on a server with known conditions (or the test server), please request reopen or submit a new report.
